---
sidebar_position: 36
---

> Create by **fall** on 23 Nov 2021
> Recently revised in 07 Apr 2023

## 调试错误的方法

可以通过 `F12` 打开调试窗口进行调试

> anonymous 表示匿名的

### Error

```js
new Error('你的年龄太小了，看不得')
// Error: 你的年龄太小了，看不得
//     <anonymous> debugger eval code:1
new TypeError('类型错误！')
```

这些内置的错误信息都继承自 `Error` 类

- **RangeError**：数字类型变量，或者参数超出有效范围时
- **ReferenceError**：引用出现错误时抛出该错误
- **SyntaxError**：解析无效 JavaScript 代码是，会出现该错误
- **TypeError**：变量或者是参数不是有效的类型时
- **URIError**：传入无效的参数至 `encodeURI()` 和 `decodeURI()` 

```ts
'use strict';
console.log.apply(console, new Array(1000000000)); // RangeError: 数组长度无效
console.log(notValidVar); // ReferenceError: notValidVar 未定义
1 *** 3 // SyntaxError: 无效的标记 *
'1.2'.toPrecision(1) // TypeError: '1.2'.toPrecision 不是函数
// 传入无效的参数至 `encodeURI()` 和 `decodeURI()` 时，会出现 `URIError` 的错误提示：
decodeURI('%') // URIError: URL 异常
```

**Error Cause**

如果自定义抛出错误，会导致原本的错误内容消失，因此添加 cause 后，可以保留浏览器抛出的错误

```js
try {
  maybeWorks();
} catch (err) {
  throw new Error('maybeWorks failed!', { cause: err });
}
```

### throw

```js
let a = '你太小了'
throw a
// Uncaught 你太小了
throw new Error('请勿靠近！')
```

尽量抛出，或者是返回 Error 对象，或者是继承 Error 对象的其他错误对象，以便于调试

### try & catch

在传输过程中可能出现错误，应用在ajax的兼容和新添加代码块时，可以使用，避免错误影响过大

执行过程

- 先执行try中的代码
- try中代码正常，不执行catch中的代码
- try中代码出现错误，直接执行catch中的代码进行补救

```js
try{
    // 尝试执行
}catch(error){
    // error 错误对象，try括号中代码执行的异常信息
}
```

相比于 if else 判断， try catch 效率更高，更加适合执行流程

try_throw_catch

throw 抛出异常

```js
try{
  alert("这里有个错误");
  throw new Error("别紧张，只是演习");
  alert("怎么会来到了错误后面");
}catch(error){
  alert("补救代码,"+error)
}
```

### debugger

相当于一个断点，程序执行到 debugger 的时候会暂停

```js
// 当在某一点的时候，如果你不想要执行，可以直接使用 debugger 进行调试

debugger
```

### finally

在 Promise 中进行使用，无论请求成功或者失败，都会执行的内容

```js
axios.get('https://www.baidu.com').then(res=>{
  // do something
}).catch(res=>{
  // do something handle the error
}).finally(()=>{
  // the thing always do after quest
})
```

### 更好地捕获错误

为了确保下一个开发者能够看懂，需要避免

```js
// 同时捕获两个函数，可能不清楚哪个函数会抛出异常
try{
  const foo = task()
  const bar = task()
}catch(e){
  console.log('Error: ',e)
}
```

改进：为每一个可能抛出异常的代码进行显示捕获

```js
try {
  const foo = runTask1();
} catch (e) {
  console.log('Error:', e);
}

try {
  const bar = runTask2();
} catch (e) {
  console.log('Error:', e);
}
```

## 浏览器兼容

> 可在该文章内查看浏览器兼容的详情：[浏览器的兼容问题及解决方案整理（建议收藏）](https://juejin.cn/post/6972937716660961317)

现如今，IE 浏览器已经停止维护，大多数现代浏览器 API 都遵从 ES6 开发规范，作为开发者，尽量避免使用规范以外的内容，即可减少不必要的兼容。

### 判断是什么浏览器

如何获取是使用的那个浏览器？

`navigator.userAgent` 能够判断是那种浏览器。比如说：

```
// qq 浏览器的 userAgent
mozilla/5.0 (iphone; cpu iphone os 11_1_2 like mac os x) applewebkit/604.3.5 (khtml, like gecko) mobile/15b202 qq/7.5.8.422 v1_iph_sq_7.5.8_1_app_a pixel/1080 core/uiwebview device/apple(iphone 8plus) nettype/wifi qbwebviewtype/1
// 微信内置浏览器
mozilla/5.0 (iphone; cpu iphone os 11_1_2 like mac os x) applewebkit/604.3.5 (khtml, like gecko) mobile/15b202 micromessenger/6.6.6 nettype/wifi language/zh_cn
```

使用浏览器 userAgent 中独有的数据段来确保浏览器的类型

```js
let agent = navigator.userAgent.toLowerCase()
const isQQBrowser = agent.includes('15b202 qq') // 为 true 则表明是 qq 浏览器
const isWechat = agent.includes('15b202 micromessenger')
```

### 插件兼容

> 更多详情可以查看[【前端开发工具】](../npm 包/babel.md)章节

在实际项目中，通过两个组件实现向下兼容。

babel 作用于语法，实现新的语法兼容。

core.js 作用于 API，比如说 Fetch 或者是 Proxy 等 API 的实现。

## 参考文章

| 作者    | 链接                                       |
| ------- | ------------------------------------------ |
| OBKoro1 | https://juejin.cn/post/6844903602591383565 |

